version: '3.1'

services:
  db:
    image: postgres:14.5
    container_name: test2
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_PASSWORD=postgres

      # - DB_PORT=5432
    restart: always

